# Generated by Django 3.2.7 on 2021-09-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientecedula', models.CharField(max_length=13)),
                ('clientenombre', models.CharField(max_length=150)),
                ('clientetelefono', models.CharField(max_length=50)),
                ('clienteanulado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gruponombre', models.CharField(max_length=150)),
                ('grupoanulado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productosnombre', models.CharField(max_length=150)),
                ('productospreciovta', models.FloatField()),
                ('productoscodigo', models.CharField(max_length=50)),
                ('productosexistencia', models.IntegerField()),
                ('productosanulado', models.CharField(max_length=1)),
                ('productosgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedorcedula', models.CharField(max_length=13)),
                ('proveedornombres', models.CharField(max_length=150)),
                ('proveedortelefono', models.CharField(max_length=50)),
                ('proveedoranulado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ventatienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventastiendafechaventa', models.DateField(blank=True, null=True)),
                ('ventatiendaobservacion', models.CharField(max_length=150)),
                ('ventanofactura', models.CharField(max_length=50)),
                ('ventatiendafechafactura', models.DateField()),
                ('ventatiendacsubtotal', models.FloatField(default=0)),
                ('ventatiendacdescuento', models.FloatField(default=0)),
                ('ventatiendatotal', models.FloatField(default=0)),
                ('ventatiendaclientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='ventadetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventadetallecantidad', models.IntegerField()),
                ('ventadetalleprecio', models.FloatField()),
                ('ventadetallesubtotal', models.FloatField()),
                ('ventadetalledescuento', models.FloatField()),
                ('ventadetalleproductos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('ventadetalleventatienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ventatienda')),
            ],
        ),
        migrations.CreateModel(
            name='comprastien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprastienfechacompras', models.DateField(blank=True, null=True)),
                ('comprastienobservacion', models.CharField(max_length=150)),
                ('comprasnofactura', models.CharField(max_length=50)),
                ('comprastienfechafactura', models.DateField()),
                ('comprastiensubtotal', models.FloatField(default=0)),
                ('comprastiendescuento', models.FloatField(default=0)),
                ('comprastientotal', models.FloatField(default=0)),
                ('comprastienproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='comprasdetalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprasdetallecantidad', models.IntegerField()),
                ('comprasdetalleprecio', models.FloatField()),
                ('comprasdetallesubtotal', models.FloatField()),
                ('comprasdetalledescuento', models.FloatField()),
                ('comprasdetallecomprastienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.comprastien')),
                ('comprasdetalleproductos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
    ]
