# Generated by Django 3.2.7 on 2021-10-16 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiantenombre', models.CharField(max_length=150)),
                ('estudianteapellido', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materianombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='clientes',
            name='clienteanulado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', help_text='Seleccione el Estado', max_length=1),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='grupoanulado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', help_text='Seleccione el Estado', max_length=1),
        ),
        migrations.AlterField(
            model_name='productos',
            name='productosanulado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', help_text='Seleccione el Estado', max_length=1),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='proveedoranulado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', help_text='Seleccione el Estado', max_length=1),
        ),
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaestudiante', models.CharField(max_length=150)),
                ('ventadetalleproductos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estudiante')),
                ('ventadetalleventatienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.materia')),
            ],
        ),
    ]
